<?php

namespace Hack\Bundle\ProxyBundle\Entity;

/**
 * GameResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameResultRepository extends \Doctrine\ORM\EntityRepository
{
}
