<?php

namespace Hack\Bundle\ProxyBundle\Entity;

/**
 * UserStatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatisticRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTop10ByScore()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select(array('p'))
            ->from('HackProxyBundle:UserStatistic', 'p')
            ->orderBy('p.score', 'DESC')
            ->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }
}
